stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/caches

build-job:
  stage: build
  script:
    - echo "Building...."
    - gradle build -x test --info
    - echo "END of Build...."
  when: manual # This setting turns a job into a manual one

unit-tests-job:
  stage: test
  script:
    - echo "Starting execution of unit tests...."
    - gradle test --tests 'gr.*'
    - echo "Execution of unit tests finished...."
  when: manual # This setting turns a job into a manual one
